CREATE TABLE [dbo].[DB_INFO] (
	NAME varchar(100) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL,
	VALUE varchar(255) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL,
	CONSTRAINT DB_INFO_PK PRIMARY KEY (NAME)
);
INSERT INTO [dbo].[DB_INFO] (NAME, VALUE) VALUES ('VERSION', 'v2');
ALTER TABLE COMPANY_INFO ADD REMARK varchar(255) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;

EXEC sp_RENAME 'RECEIPT_INFO.DATE' , 'DATE_2', 'COLUMN';
ALTER TABLE RECEIPT_INFO ADD RECEIPT_DATE varchar(255) COLLATE Chinese_Taiwan_Stroke_CI_AS NULL;
UPDATE RECEIPT_INFO SET RECEIPT_DATE = convert(varchar, DATE_2, 111);
ALTER TABLE RECEIPT_INFO DROP COLUMN DATE_2;